### ISSUE TITLE
Having issue with hexcode and text line up in Fedora 19

### ISSUE THREAD

**Issue by nedzhang** [AbeEstrada/atom-hex#13]
Great product! I love the ability to see the hex code. 

For some reason, the text as not line up correctly. It looks like that they are not monospace fonts.

![screenshot from 2015-01-22 13 15 33](https://cloud.githubusercontent.com/assets/7337234/5862614/e1350a8c-a238-11e4-8598-b21e1f92c97b.png)

Regular files shows up correctly with monospace font. Here is the screenshot.

![screenshot from 2015-01-22 13 15 58](https://cloud.githubusercontent.com/assets/7337234/5862626/fc170846-a238-11e4-9889-b0bb26b418d0.png)

Let me know if there is anything I need to fix. Maybe need to install a font?

Thanks!

**Comment by AbeEstrada** [comment]
It uses the font defined in your configuration.

https://github.com/AbeEstrada/atom-hex/blob/master/lib/hex-view.coffee#L20

I'm going to take a look to see if the API changed.

**Comment by AbeEstrada** [comment]
Please open the Developer Tools and run this command `atom.config.get("editor.fontFamily")` and paste the result here.

I want to see what it returns, because that's the font that it is supposed to use `atom-hex`.

![screen shot 2015-01-22 at 12 54 36 pm](https://cloud.githubusercontent.com/assets/7937/5863311/e6c91766-a235-11e4-83bd-9fc1639c3c94.png)

**Comment by nedzhang** [comment]
Looks like it is not set.

![image](https://cloud.githubusercontent.com/assets/7337234/5868928/b237a332-a276-11e4-998d-59c924cfce6f.png)

**Comment by AbeEstrada** [comment]
I added a default `font-family` for those cases.

**Comment by nedzhang** [comment]
I have monospace font now.
